{% set name = "types-annoy" %}
{% set version = "1.17.8.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-annoy-{{ version }}.tar.gz
  sha256: 3cb135d7b5fdda0c87fea9bf5cbeb6eead3f7d880cc7c9e3e9fe7ab06d8f5a0b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/annoy-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for annoy
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
