{% set name = "types-annoy" %}
{% set version = "1.17.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-annoy-{{ version }}.tar.gz
  sha256: 49753276028c4fe6af8ba7161d9a867c7bb8fb979e6174637d69b20e21e12a20

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/annoy-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for annoy
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
